# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: Aniketwarule775@gmail.com
author_name: Aniket Warule
contract_name: crazy_contract
deployment_language: python
preset_name: starter
project_name: donation_contract

